import './globals.css'
import type { Metadata } from 'next'
import NavBar from '../components/NavBar'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html className="box-border" lang="en">
      <body className="h-screen w-screen box-border m-0 p-0 overflow-hidden">
        <NavBar />
        {children}
      </body>
    </html>
  )
}
